version: "3.3"

services:
  postgres:
    container_name: "postgres"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - "./psql_volume:/db"
  
  neo4j:
    image: neo4j:3.5.15
    container_name: "neo4j"
    environment:
      NEO4J_AUTH: neo4j/test
    ports:
      - 7474:7474
      - 7687:7687 
    volumes:
      - type: bind
        source: "./tables/db"
        target: "/var/lib/neo4j/import/"
        read_only: true